Path = "/home/qmiao/Desktop/n3-csv2json/Server/go-client/config.toml"
LogFile = "./go-clt-CSV2JSON-[DATE].log"
ServiceName = "N3-CSV2JSON"

[Server]
  Protocol = "http"
  IP = "192.168.31.168"
  Port = 1325

[Access]
  Timeout = 3

[Route]
  HELP = "/"
  CSV2JSON = "/csv2json/v0.1.1"
  JSON2CSV = "/json2csv/v0.1.1"
