Path = "/home/qmiao/Desktop/n3-csv2json/Server/go-client/config.toml"
Service = "n3-csv2json"

[Server]
  Protocol = "http"
  IP = "192.168.31.168"
  Port = 1325

[Access]
  Timeout = 3

[Route]
  HELP = "/"
  CSV2JSON = "/n3-csv2json/v0.2.1/csv2json"
  JSON2CSV = "/n3-csv2json/v0.2.1/json2csv"
