Service = "n3-csv2json"

[Route]
  Help = "/"
  ToCSV = "/n3-csv2json/v0.3.1/2csv"
  ToJSON = "/n3-csv2json/v0.3.1/2json"

[Server]
  Protocol = "http"
  IP = "192.168.31.168"
  Port = 1325

[Access]
  Timeout = 3
