Path = "/home/qmiao/go/src/github.com/nsip/n3-csv2json/Server/config/config.toml"
LogFile = "/home/qmiao/go/src/github.com/nsip/n3-csv2json/[DATE].log"
ServiceName = "N3-CSV2JSON"

[WebService]
  Port = 1325
  Version = "0.1.0"

[Route]
  HELP = "/"
  CSV2JSON = "/csv2json/[v]"
  JSON2CSV = "/json2csv/[v]"

[NATS]
  URL = "nats://192.168.78.130:4222"
  Subject = "CSV2JSON"
  Timeout = 500

[File]
  ClientLinux64 = "../../../Client/build/linux64/client"
  ClientMac = "../../../Client/build/mac/client"
  ClientWin64 = "../../../Client/build/win64/client.exe"
  ClientConfig = "../../../Client/build/linux64/config.toml"
