Path = "/home/qmiao/Desktop/n3-csv2json/Server/config/config.toml"
Service = "n3-csv2json"
Log = "~/.[s]/log/[DATE].log"
Version = "v0.2.4"

[Loggly]
  Token = "54290728-93e0-425a-a49c-c9e834288026"

[WebService]
  Port = 1325

[NATS]
  URL = "nats://192.168.78.130:4222"
  Subject = "CSV2JSON"
  Timeout = 500

[Route]
  HELP = "/"
  CSV2JSON = "/[s]/[v]/csv2json"
  JSON2CSV = "/[s]/[v]/json2csv"

[Server]
  IP = "[IP]"
  Port = 1325
  Protocol = "http"

[Access]
  Timeout = 3
