Service = "n3-csv2json"
Path = "/home/qmiao/Desktop/n3-csv2json/Server/config/config.toml"

[Route]
  HELP = "/"
  CSV2JSON = "/n3-csv2json/v0.3.0/csv2json"
  JSON2CSV = "/n3-csv2json/v0.3.0/json2csv"

[Server]
  IP = "192.168.31.168"
  Port = 1325
  Protocol = "http"

[Access]
  Timeout = 3
