Path = "[PATH]"
Service = "[PRJ]"
Log = "~/.[PRJ]/log/[DATE].log"
Version = "[VER]"

[Loggly]
  Token = "54290728-93e0-425a-a49c-c9e834288026"

[WebService]
  Port = 1325

[NATS]
  URL = "nats://192.168.78.130:4222"
  Subject = "CSV2JSON"
  Timeout = 500

[Route]
  HELP = "/"
  CSV2JSON = "/[PRJ]/[VER]/csv2json"
  JSON2CSV = "/[PRJ]/[VER]/json2csv"

[Server]
  IP = "[IP]"
  Port = 1325
  Protocol = "http"

[Access]
  Timeout = 3
