Log = "~/.[PRJ]/log/[DATE].log"
Service = "[PRJ]"
Version = "[VER]"

[Loggly]
Token = "54290728-93e0-425a-a49c-c9e834288026"

[WebService]
Port = 1325

[NATS]
Subject = "CSV2JSON"
Timeout = 500
URL = "nats://192.168.78.130:4222"

[Route]
Help = "/"
ToCSV = "/[PRJ]/[VER]/2csv"
ToJSON = "/[PRJ]/[VER]/2json"

[Server]
IP = "[IP]"
Port = 1325
Protocol = "http"

[Access]
Timeout = 3
